"""add_branches_and_branch_scoping

Revision ID: c8824fe50c81
Revises: d1d7921aecae
Create Date: 2026-05-22 14:22:51.132489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8824fe50c81'
down_revision: Union[str, Sequence[str], None] = 'd1d7921aecae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('bot_name', sa.String(length=100), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('is_main_branch', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_slug'), 'branches', ['slug'], unique=True)
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('flagged_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('flagged_message', sa.Text(), nullable=True),
    sa.Column('intercepted_response', sa.Text(), nullable=True),
    sa.Column('safe_response', sa.Text(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flagged_logs_branch_id'), 'flagged_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_flagged_logs_created_at'), 'flagged_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_flagged_logs_flag_type'), 'flagged_logs', ['flag_type'], unique=False)
    op.create_index(op.f('ix_flagged_logs_session_token'), 'flagged_logs', ['session_token'], unique=False)
    op.create_index(op.f('ix_flagged_logs_tenant_id'), 'flagged_logs', ['tenant_id'], unique=False)
    op.add_column('appointments', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_appointments_tenant'), table_name='appointments')
    op.create_index(op.f('ix_appointments_branch_id'), 'appointments', ['branch_id'], unique=False)
    op.create_index('uq_active_appointment_slot', 'appointments', ['tenant_id', 'doctor_id', 'slot_datetime'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.create_foreign_key(None, 'appointments', 'branches', ['branch_id'], ['id'])
    op.add_column('chat_sessions', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_chat_sessions_tenant'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_token'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_branch_id'), 'chat_sessions', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'branches', ['branch_id'], ['id'])
    op.add_column('doctors', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_doctors_tenant'), table_name='doctors')
    op.create_index(op.f('ix_doctors_branch_id'), 'doctors', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'doctors', 'branches', ['branch_id'], ['id'])
    op.add_column('invoices', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invoices_branch_id'), 'invoices', ['branch_id'], unique=False)
    op.create_unique_constraint('uq_invoice_number_tenant', 'invoices', ['tenant_id', 'invoice_number'])
    op.create_foreign_key(None, 'invoices', 'branches', ['branch_id'], ['id'])
    op.add_column('leads', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_leads_tenant'), table_name='leads')
    op.create_index(op.f('ix_leads_branch_id'), 'leads', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'branches', ['branch_id'], ['id'])
    op.drop_column('leads', 'visit_count')
    op.drop_column('leads', 'condition')
    op.drop_column('leads', 'is_existing_patient')
    op.drop_column('leads', 'last_visit')
    op.add_column('patients', sa.Column('primary_branch_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('patients_tenant_id_phone_key'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_primary_branch_id'), 'patients', ['primary_branch_id'], unique=False)
    op.create_foreign_key(None, 'patients', 'branches', ['primary_branch_id'], ['id'])
    op.add_column('users', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    op.add_column('visit_records', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_visit_records_branch_id'), 'visit_records', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'visit_records', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_records', type_='foreignkey')
    op.drop_index(op.f('ix_visit_records_branch_id'), table_name='visit_records')
    op.drop_column('visit_records', 'branch_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_column('users', 'branch_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_primary_branch_id'), table_name='patients')
    op.create_unique_constraint(op.f('patients_tenant_id_phone_key'), 'patients', ['tenant_id', 'phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'primary_branch_id')
    op.add_column('leads', sa.Column('last_visit', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('is_existing_patient', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('visit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_branch_id'), table_name='leads')
    op.create_index(op.f('idx_leads_tenant'), 'leads', ['tenant_id'], unique=False)
    op.drop_column('leads', 'branch_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint('uq_invoice_number_tenant', 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_branch_id'), table_name='invoices')
    op.drop_column('invoices', 'branch_id')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_branch_id'), table_name='doctors')
    op.create_index(op.f('idx_doctors_tenant'), 'doctors', ['tenant_id'], unique=False)
    op.drop_column('doctors', 'branch_id')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_branch_id'), table_name='chat_sessions')
    op.create_index(op.f('idx_chat_sessions_token'), 'chat_sessions', ['session_token'], unique=False)
    op.create_index(op.f('idx_chat_sessions_tenant'), 'chat_sessions', ['tenant_id'], unique=False)
    op.drop_column('chat_sessions', 'branch_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index('uq_active_appointment_slot', table_name='appointments', postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.drop_index(op.f('ix_appointments_branch_id'), table_name='appointments')
    op.create_index(op.f('idx_appointments_tenant'), 'appointments', ['tenant_id'], unique=False)
    op.drop_column('appointments', 'branch_id')
    op.drop_index(op.f('ix_flagged_logs_tenant_id'), table_name='flagged_logs')
    op.drop_index(op.f('ix_flagged_logs_session_token'), table_name='flagged_logs')
    op.drop_index(op.f('ix_flagged_logs_flag_type'), table_name='flagged_logs')
    op.drop_index(op.f('ix_flagged_logs_created_at'), table_name='flagged_logs')
    op.drop_index(op.f('ix_flagged_logs_branch_id'), table_name='flagged_logs')
    op.drop_table('flagged_logs')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_slug'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
